### PR TITLE
Stage 2 JSX and Markup 

### PR DESCRIPTION
**Pull request by vakhitovalex**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Good job! Some corrections need to be made, but on the whole, the project is very impressive, awesome responsive layout!

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
* There should be no "Saved articles" link in the header when the user isn't logged in: http://joxi.ru/8AnK1e1UyBqMkr
* On the other hand, there should be no "Sign in" button when he's logged in.
* The cards should be aligned to the left inside their container: http://joxi.ru/n2Ywp3pCeYjKZr
* Saved-articles header should have this block: http://joxi.ru/LmGwO1OClyREem before the cards list.
* The content of the page should have limited width. Currenlty, on large screen resolutions, it's stretched to the whole width (e.g. on 2800px the content in header, cards (the title), author, will occupy the whole screen width). The backround in the header however can be stretched to occupy the whole screen (or it can be limited, too, it's up to you)
* On mobile screens, the input and button inside "search" form should be bigger (higher), please check the design.
* On saved-articles page, the card should have a trash can icon instead of a bookmark.
* No burger-menu icon is displayed in the header of "saved-articles" on mobile screens. And besides, the menu itself looks different from the mockup: http://joxi.ru/Q2KwkNkCvz9Vw2
- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
* "Registration successful" popup isn't coded
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
* Should be a list: http://joxi.ru/V2Vw0Z0Ck10wxA. The links in the footer should be inside a list, too.
* Should be a heading: http://joxi.ru/a2XwjRjC4xyN3m http://joxi.ru/Rmz7j4jiM60W52 http://joxi.ru/DmB9KOKs4XwNkr
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.
* The Sign Up popup doesnt open on clicking this link: http://joxi.ru/8AnK1e1UyBqJjr
* "Registration successful" popup isn't coded
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.	
- Your project contains:
	- [x]  An images folder
	- [ ]  A components folder with JS and CSS files for the components.
	* Should be moved to correspondent components http://joxi.ru/Dr8qz5zcMV4opm
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.
* Elements are used outside of their blocks: http://joxi.ru/a2XwjRjC4xyE3m
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
* Search button doesn't have hover and active states.
* When not logged in, the bookmark on the card on hover: http://joxi.ru/Dr8qz5zcMVkezm
* Trash can icon on hover: http://joxi.ru/YmEwlxlCMnZ8jA
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [ ]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [ ]  System fonts are connected as alternatives to each of your fonts.
* Please find and correct all similar issues: http://joxi.ru/VrwkG4Gh4BO4Zr
- [x]  Raster and vector images have been optimized.

## Number of points: 53

## Additional comments:
An empty checkbox hidden by css in the navigation `nav__checkbox` isn't needed, would be better to remove it.

**Comment by vakhitovalex** [comment]
> Re this: 
An empty checkbox hidden by css in the navigation nav__checkbox isn't needed, would be better to remove it.

Я использовал checkbox вместе с label, чтобы сделать мобильное меню используя pure css. Надо было через реакт, но так много времени на этот checkbox & label потратил, что хочется оставить так :crying_cat_face:

**Comment by ImaliaNsk** [comment]
Hi! Thanks for the corrections, good job! However, there are still some issues to be corrected and some more appeared as a result of corrections. Please, remember to reset the default styles for elements like `ul`

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
* horizontal scroll on resolutions 1456px and smaller (please, remember to remove the default padding for the elements marked up as `ul`)
* on desktop resolutions there should be 3 cards in a row: http://joxi.ru/BA0xqPqHvl4wnA. This is an example resolution, please check all desktop screens and make sure cards list displays three cards in a row.
* on tablet resolutions there should be 3 cards in a row: http://joxi.ru/Rmz7j4jijXOGy2
* a horizontal scroll on mobile screens: http://joxi.ru/EA4l0P0UvPaxPA
* When logged in, the burger menu lacks the link to "Saved articles" page
* No burger-menu icon is displayed in the header of "saved-articles" on mobile screens. And besides, the menu itself looks different from the mockup: http://joxi.ru/Q2KwkNkCvz9Vw2
* Sign In popup has incorrect title, button and link text: http://joxi.ru/KAgwR4RCNn96oA. This is the "Sign In" popup, and it should have the link to "Sign Up". Please remember that "Sign up" popup should have three fields.
- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
* "Registration successful" popup isn't coded
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
* On laptop and desktop resolutions, there should be 3 cards in a row, and besides there's a very big gap between the cards, it should be corrected: http://joxi.ru/Q2KwkNkCybWd02
- [ ]  There are no validation errors.
http://joxi.ru/8AnK1e1Uo1n0Vr
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.
* The Sign Up popup doesnt open on clicking this link: http://joxi.ru/8AnK1e1UyBqJjr
* "Registration successful" popup isn't coded
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.	
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [x]  Classes are named according to BEM specifications.
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
* Trash can icon on hover: http://joxi.ru/YmEwlxlCMnZ8jA
* When not logged in, the bookmark on the card on hover: http://joxi.ru/Dr8qz5zcMVkezm

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [ ]  The form must have placeholders, and required fields should be validated.
* required fields aren't validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 46

**Comment by ImaliaNsk** [comment]
Good job, keep it up! Resposive layout will require a bit more work.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
* There's still a horizontal scroll on resolutions 1456px and smaller, please check the width of sections and elements.
* cards container needs some side margins: http://joxi.ru/D2PwN5NCBjb89m, according to the design.
* The footer layout on mobile screens doesn't correspond to the design: http://joxi.ru/v29gb6bFRdbP6r
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
* This gap is too big: http://joxi.ru/krDvaXaTgMnq32. Please, check and correct on other resolutions too.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.	
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [x]  Classes are named according to BEM specifications.
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
* Trash can icon on hover: http://joxi.ru/YmEwlxlCMnZ8jA
* When not logged in, the bookmark on the card on hover: http://joxi.ru/Dr8qz5zcMVkezm

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [ ]  The form must have placeholders, and required fields should be validated.
* required fields aren't validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 67

**Comment by vakhitovalex** [comment]
Re this:
> * There's still a horizontal scroll on resolutions 1456px and smaller, please check the width of sections and elements.

I checked it on all possible emulated devices in chrome and firefox and there is no horizontal scroll on any resolution/device, I can provide screenshots if needed.

**Comment by ImaliaNsk** [comment]
Hi! Good job, but some issues atill persist, and a validation error appeared after the corrections.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
* There's still a horizontal scroll on resolutions 1456px and smaller http://joxi.ru/823yGPGuanW6Rr , please check the width of sections and elements. I can make an assumption why you don't see it: most probably you have a Mac, it hides the scrollbars, you can change your preferencies to show scrollbars.
* On mobile screens, the width of the cards doesn't correspond to the design: http://joxi.ru/xAe4ZqZcbJjXN2
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [ ]  There are no validation errors.
http://joxi.ru/KAx1040uvny3Qr
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.	
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [x]  Classes are named according to BEM specifications.
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
* Trash can icon on hover: http://joxi.ru/YmEwlxlCMnZ8jA
* When not logged in, the bookmark on the card on hover: http://joxi.ru/Dr8qz5zcMVkezm

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [ ]  The form must have placeholders, and required fields should be validated.
* required fields aren't validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 78

**Comment by ImaliaNsk** [comment]
Great job, the project is accepted! Good luck on the next stage!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.	
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [x]  Classes are named according to BEM specifications.
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
* Trash can icon on hover: http://joxi.ru/YmEwlxlCMnZ8jA
* When not logged in, the bookmark on the card on hover: http://joxi.ru/Dr8qz5zcMVkezm

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 98

**Pull request merged**
